using System.Text;


internal class Program
{
    private static void Main(string[] args)
    {
        try { Console.OutputEncoding = Encoding.UTF8; } catch { }

        string folder;
        if (args.Length > 0)
        {
            folder = args[0];
        }
        else
        {
            Console.WriteLine("=== C# 源文件合并工具 ===");
            Console.Write("请输入文件夹路径: ");
            folder = (Console.ReadLine() ?? string.Empty).Trim().Trim('"');
        }

        if (string.IsNullOrWhiteSpace(folder) || !Directory.Exists(folder))
        {
            Console.WriteLine("错误：文件夹不存在：" + folder);
            Pause();
            return;
        }

        folder = Path.GetFullPath(folder);
        // 生成时间戳（冒号在 Windows 文件名中非法，改为短横线）
        string timestamp = DateTime.Now.ToString("yyyy-MM-dd HH-mm-ss");
        string outputFileName = $"Merged - {timestamp}.cs";
        string outputPath = Path.Combine(folder, outputFileName);

        List<string> files;
        try
        {
            files = Directory.GetFiles(folder, "*.cs", SearchOption.AllDirectories)
                .Where(f => !IsInIgnoredFolder(f, folder))
                .Where(f => !Path.GetFileName(f).StartsWith("Merged", StringComparison.OrdinalIgnoreCase))
                .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        catch (Exception ex)
        {
            Console.WriteLine("读取目录失败: " + ex.Message);
            Pause();
            return;
        }

        if (files.Count == 0)
        {
            Console.WriteLine("该文件夹下没有找到 .cs 文件。");
            Pause();
            return;
        }

        Console.WriteLine($"找到 {files.Count} 个 .cs 文件，开始合并...");

        var usingList = new List<string>();
        var usingSet = new HashSet<string>(StringComparer.Ordinal);
        var bodies = new List<string>();
        int typeCount = 0;

        foreach (string file in files)
        {
            string text;
            try
            {
                text = File.ReadAllText(file);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"跳过 {file}: {ex.Message}");
                continue;
            }

            string rel = GetRelativePath(folder, file);

            // 1. 提取 using 指令
            List<UsingDirective> usings = ExtractUsings(text);
            foreach (UsingDirective u in usings)
            {
                string norm = NormalizeWhitespace(u.Text);
                if (usingSet.Add(norm))
                    usingList.Add(norm);
            }

            // 2. 去掉 using 指令
            string body = RemoveUsings(text, usings);

            // 3. 在每个 class / struct 前插入来源注释
            body = InsertSourceComments(body, rel, ref typeCount);

            body = body.Trim('\r', '\n', ' ', '\t');
            if (body.Length > 0)
                bodies.Add(body);
        }

        // 4. 拼装结果
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     本文件由 C# 源文件合并工具自动生成。");
        sb.AppendLine("//     生成时间：" + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        foreach (string u in usingList)
            sb.AppendLine(u);
        if (usingList.Count > 0)
            sb.AppendLine();

        foreach (string body in bodies)
        {
            sb.AppendLine(body);
            sb.AppendLine();
        }

        try
        {
            File.WriteAllText(outputPath, sb.ToString(), new UTF8Encoding(true));
        }
        catch (Exception ex)
        {
            Console.WriteLine("写入失败: " + ex.Message);
            Pause();
            return;
        }

        Console.WriteLine($"合并完成：{files.Count} 个文件，{typeCount} 个 class/struct。");
        Console.WriteLine("输出文件: " + outputPath);
        Pause();
    }

    // ---------------- 主体逻辑 ----------------

    /// <summary>从源码中提取所有 using 指令（包括 global using）</summary>
    private static List<UsingDirective> ExtractUsings(string s)
    {
        var result = new List<UsingDirective>();
        int i = 0, n = s.Length;

        while (i < n)
        {
            char c = s[i];

            if (c == '/' && i + 1 < n && s[i + 1] == '/')
            {
                i += 2;
                while (i < n && s[i] != '\n') i++;
                continue;
            }
            if (c == '/' && i + 1 < n && s[i + 1] == '*')
            {
                i += 2;
                while (i + 1 < n && !(s[i] == '*' && s[i + 1] == '/')) i++;
                i = Math.Min(n, i + 2);
                continue;
            }
            if (IsLiteralStart(s, i))
            {
                i = SkipLiteral(s, i);
                continue;
            }

            if (char.IsLetter(c) || c == '_')
            {
                int start = i;
                while (i < n && (char.IsLetterOrDigit(s[i]) || s[i] == '_')) i++;
                string word = s.Substring(start, i - start);

                if (word == "class" || word == "struct")
                {
                    // 确认是类型声明（而不是 where T : class 里的约束）
                    int j = i;
                    while (j < n && char.IsWhiteSpace(s[j])) j++;
                    if (j < n && (char.IsLetter(s[j]) || s[j] == '_'))
                        break; // 遇到第一个类型声明，后面的 using 不再收集
                }
                else if (word == "using")
                {
                    // 排除 using 语句：using (xxx)  /  using var x = ...
                    int k = i;
                    while (k < n && char.IsWhiteSpace(s[k])) k++;
                    if (k < n && s[k] == '(')
                        continue;

                    int dirStart = start;

                    // 处理 "global using"
                    int p = start - 1;
                    while (p >= 0 && char.IsWhiteSpace(s[p])) p--;
                    int wordEnd = p;
                    while (p >= 0 && (char.IsLetterOrDigit(s[p]) || s[p] == '_')) p--;
                    if (wordEnd > p && s.Substring(p + 1, wordEnd - p) == "global")
                        dirStart = p + 1;

                    int semi = s.IndexOf(';', i);
                    if (semi < 0) break;

                    result.Add(new UsingDirective
                    {
                        Start = dirStart,
                        End = semi + 1,
                        Text = s.Substring(dirStart, semi + 1 - dirStart)
                    });

                    i = semi + 1;
                    continue;
                }
                continue;
            }

            i++;
        }

        return result;
    }

    /// <summary>删除 using 指令（连同其后换行）</summary>
    private static string RemoveUsings(string text, List<UsingDirective> usings)
    {
        if (usings.Count == 0) return text;

        var sb = new StringBuilder();
        int pos = 0;
        foreach (UsingDirective u in usings.OrderBy(x => x.Start))
        {
            if (u.Start < pos) continue;
            sb.Append(text, pos, u.Start - pos);
            pos = u.End;
            while (pos < text.Length && (text[pos] == '\r' || text[pos] == '\n')) pos++;
        }
        sb.Append(text, pos, text.Length - pos);
        return sb.ToString();
    }

    /// <summary>在文本中找到所有 class / struct 声明的位置</summary>
    private static List<int> FindTypeDeclarations(string s)
    {
        var result = new List<int>();
        int i = 0, n = s.Length;

        while (i < n)
        {
            char c = s[i];

            if (c == '/' && i + 1 < n && s[i + 1] == '/')
            {
                i += 2;
                while (i < n && s[i] != '\n') i++;
                continue;
            }
            if (c == '/' && i + 1 < n && s[i + 1] == '*')
            {
                i += 2;
                while (i + 1 < n && !(s[i] == '*' && s[i + 1] == '/')) i++;
                i = Math.Min(n, i + 2);
                continue;
            }
            if (IsLiteralStart(s, i))
            {
                i = SkipLiteral(s, i);
                continue;
            }

            if (char.IsLetter(c) || c == '_')
            {
                int start = i;
                while (i < n && (char.IsLetterOrDigit(s[i]) || s[i] == '_')) i++;
                string word = s.Substring(start, i - start);

                if (word == "class" || word == "struct")
                {
                    int j = i;
                    while (j < n && char.IsWhiteSpace(s[j])) j++;
                    if (j < n && (char.IsLetter(s[j]) || s[j] == '_'))
                        result.Add(start);
                }
                continue;
            }

            i++;
        }

        return result;
    }

    /// <summary>在每个类型声明前插入来源注释</summary>
    private static string InsertSourceComments(string text, string sourceName, ref int typeCount)
    {
        List<int> positions = FindTypeDeclarations(text);
        if (positions.Count == 0) return text;

        typeCount += positions.Count;

        string comment =
            "//====================\r\n" +
            "//来自于 " + sourceName + "\r\n";

        var sb = new StringBuilder(text);
        // 从后往前插入，避免下标错乱
        for (int k = positions.Count - 1; k >= 0; k--)
        {
            int insertAt = FindInsertOffset(text, positions[k]);
            sb.Insert(insertAt, comment);
        }
        return sb.ToString();
    }

    /// <summary>
    /// 计算注释插入点：跳过紧贴在类型声明上方的 XML 文档注释(///) 与单行特性([...])
    /// </summary>
    /// <summary>
    /// 计算注释插入点：跳过紧贴在类型声明上方的 XML 文档注释(///) 与单行特性([...])
    /// </summary>
    private static int FindInsertOffset(string s, int typeKeywordIndex)
    {
        int lineStart = s.LastIndexOf('\n', Math.Max(0, typeKeywordIndex - 1)) + 1;

        while (lineStart > 0)
        {
            int prevLineEnd = lineStart - 1;                 // 上一行末尾的 '\n'
            int prevLineStart = s.LastIndexOf('\n', Math.Max(0, prevLineEnd - 1)) + 1;

            // 修复：如果计算出的上一行起始位置大于上一行结束位置（例如文件以换行符开头的边界情况）
            // 则说明没有上一行可供提取，直接返回文件头部（0）
            if (prevLineStart > prevLineEnd)
            {
                lineStart = 0;
                break;
            }

            string prevLine = s.Substring(prevLineStart, prevLineEnd - prevLineStart).Trim();

            if (prevLine.StartsWith("///", StringComparison.Ordinal) ||
                (prevLine.StartsWith("[", StringComparison.Ordinal) && prevLine.EndsWith("]", StringComparison.Ordinal)))
            {
                lineStart = prevLineStart;
            }
            else
            {
                break;
            }
        }

        return lineStart;
    }

    // ---------------- 词法辅助 ----------------

    private static bool IsLiteralStart(string s, int i)
    {
        char c = s[i];
        if (c == '"' || c == '\'') return true;
        if (c == '@' && i + 1 < s.Length && s[i + 1] == '"') return true;
        if (c == '$' && i + 1 < s.Length && (s[i + 1] == '"' || s[i + 1] == '@' || s[i + 1] == '$'))
            return true;
        return false;
    }

    /// <summary>跳过字符串 / 字符字面量，返回结束后的下标</summary>
    private static int SkipLiteral(string s, int i)
    {
        int n = s.Length;
        bool verbatim = false;

        while (i < n && (s[i] == '@' || s[i] == '$'))
        {
            if (s[i] == '@') verbatim = true;
            i++;
        }
        if (i >= n) return n;

        if (s[i] == '"')
        {
            i++;
            while (i < n)
            {
                if (verbatim)
                {
                    if (s[i] == '"')
                    {
                        if (i + 1 < n && s[i + 1] == '"') { i += 2; continue; }
                        return i + 1;
                    }
                    i++;
                }
                else
                {
                    if (s[i] == '\\') { i += 2; continue; }
                    if (s[i] == '"') return i + 1;
                    i++;
                }
            }
            return n;
        }

        if (s[i] == '\'')
        {
            i++;
            while (i < n)
            {
                if (s[i] == '\\') { i += 2; continue; }
                if (s[i] == '\'') return i + 1;
                i++;
            }
            return n;
        }

        return i;
    }

    // ---------------- 杂项 ----------------

    private static string NormalizeWhitespace(string text)
    {
        string[] parts = text.Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Join(" ", parts);
    }

    private static bool IsInIgnoredFolder(string filePath, string root)
    {
        string rel = GetRelativePath(root, filePath);
        string[] parts = rel.Split(new[] { '\\', '/' }, StringSplitOptions.RemoveEmptyEntries);
        foreach (string p in parts)
        {
            if (p.Equals("bin", StringComparison.OrdinalIgnoreCase) ||
                p.Equals("obj", StringComparison.OrdinalIgnoreCase) ||
                p.Equals(".git", StringComparison.OrdinalIgnoreCase) ||
                p.Equals(".vs", StringComparison.OrdinalIgnoreCase))
                return true;
        }
        return false;
    }

    private static string GetRelativePath(string root, string fullPath)
    {
        if (!root.EndsWith(Path.DirectorySeparatorChar.ToString(), StringComparison.Ordinal))
            root += Path.DirectorySeparatorChar;

        if (fullPath.StartsWith(root, StringComparison.OrdinalIgnoreCase))
            return fullPath.Substring(root.Length);

        return fullPath;
    }

    private static void Pause()
    {
        Console.WriteLine("按任意键退出...");
        try { Console.ReadKey(true); } catch { }
    }

    private class UsingDirective
    {
        public int Start;
        public int End;
        public string Text = string.Empty;
    }
}
